name: Build / RadioTime Plugin

on:
  push:
    # On Push to Master branch
    branches: 
      - master
    # Ignore all Tags / Release
    tags-ignore:
      - '**'

  workflow_call:
    inputs:
      retention-build:
        description: "Retention Period for Setup files. Default is 90"
        default: 90
        required: false
        type: number
    outputs:
      version:
        description: "MPE1 Version"
        value: ${{ jobs.mpe.outputs.version }}

jobs:
  build:
    name: RadioTime Plugin / Build
    runs-on: windows-2019
    steps:
      - name: Setup Visual Studio 2019
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 16.11

      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          build_git.bat < nul
        working-directory: ${{ github.workspace }}\setup
        shell: cmd

      - name: Upload Artifact / Plugin
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: RadioTimePlugin
          path: |
            ${{ github.workspace }}\RadioTimePlugin\bin\Release\RadioTimePlugin.dll
            ${{ github.workspace }}\RadioTimePlugin\bin\Release\RadioTimeOpmlApi.dll
          retention-days: ${{ inputs.retention-build || 90 }}
          if-no-files-found: error

      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}
          key: plugin

  codeql:
    name: CodeQL
    if: "contains(github.event.head_commit.message, '[release]')"
    uses: andrewjswan/MPE/.github/workflows/codeql.yml@master
    with:
      build-path: setup
    needs: 
      - build
    permissions:
      security-events: write
    secrets: inherit

  mpe:
    name: RadioTime Plugin / MPE
    runs-on: windows-2019
    needs:
      - build
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}
          key: plugin

      - name: Git Checkout / MPE / XPath
        uses: actions/checkout@v4
        with:
          repository: andrewjswan/MPE
          path: MPE

      - name: MP folder for MPEMaker
        run: |
          mkdir "C:\Team MediaPortal"
        shell: cmd

      - name: Link to MPEMaker
        run: |
          mklink /J "C:\Team MediaPortal\MediaPortal" "${{ github.workspace }}\MPE\MPEMaker"
        shell: cmd

      - name: Clear Build folder
        run: |
          del /F /Q *.*
        working-directory: ${{ github.workspace }}\setup\builds
        shell: cmd

      - name: Get MPE1 Version
        id: version
        run: |
          FOR /F "tokens=*" %%i IN ('Tools\sigcheck.exe -accepteula -nobanner -n "..\RadioTimePlugin\bin\Release\RadioTimePlugin.dll"') DO (ECHO version=%%i >> %GITHUB_OUTPUT%)
        working-directory: ${{ github.workspace }}\setup
        shell: cmd

      - name: Build MPE1
        run: |
          Create_Installer.bat
        working-directory: ${{ github.workspace }}\setup
        shell: cmd

      - name: Upload Artifact / MPE1
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: RadioTimePlugin MPE1
          path: |
            ${{ github.workspace }}\setup\builds\RadioTime-*.mpe1
          retention-days: ${{ inputs.retention-build || 90 }}
          if-no-files-found: error

      - name: Upload Artifact / MPE XML
        uses: actions/upload-artifact@v4
        if: ${{ success() && contains(github.event.head_commit.message, '[release]') }}
        with:
          name: RadioTimePlugin XML
          path: |
            ${{ github.workspace }}\setup\RadioTimePlugin.xml
          retention-days: ${{ inputs.retention-build || 90 }}
          if-no-files-found: error

      - name: Get Release Version Description
        if: ${{ success() && contains(github.event.head_commit.message, '[release]') }}
        run: |
          call ..\MPE\XPath\xpath.cmd "RadioTimePlugin.xml" "//Items/PackageClass/GeneralInfo/VersionDescription" last > description.txt
        working-directory: ${{ github.workspace }}\setup
        shell: cmd

      - name: Clean Release Version Description
        if: ${{ success() && contains(github.event.head_commit.message, '[release]') }}
        run: |
          sed.exe -i "s/\*\*\* We Stand with Ukraine \*\*\*//g" description.txt
        working-directory: ${{ github.workspace }}\setup
        shell: cmd

      - name: Add Badges to Release Version Description
        if: ${{ success() && contains(github.event.head_commit.message, '[release]') }}
        run: |
          ECHO [![Downloads](https://img.shields.io/github/downloads/andrewjswan/mediaportal-tunein/v${{steps.version.outputs.version}}/total)](https://github.com/andrewjswan/mediaportal-tunein/releases/tag/v${{steps.version.outputs.version}}) [![StandWithUkraine](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/StandWithUkraine.svg)](https://github.com/vshymanskyy/StandWithUkraine/blob/main/docs/README.md) >> description.txt
        working-directory: ${{ github.workspace }}\setup
        shell: cmd

      - name: Clean Release Version Description
        if: ${{ success() && contains(github.event.head_commit.message, '[release]') }}
        run: |
          sed.exe -i "s/ \//\//g" description.txt
        working-directory: ${{ github.workspace }}\setup
        shell: cmd

      - name: Upload Artifact / Version Description
        uses: actions/upload-artifact@v4
        if: ${{ success() && contains(github.event.head_commit.message, '[release]') }}
        with:
          name: RadioTimePlugin Version Description
          path: |
            ${{ github.workspace }}\setup\description.txt
          retention-days: ${{ inputs.retention-build || 90 }}
          if-no-files-found: error

  xml:
    name: RadioTime Plugin / XML
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[release]')"
    needs:
      - mpe
    permissions:
      contents: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: RadioTimePlugin XML
          path: ${{ github.workspace }}/setup/

      - name: Update / MPE1 XML
        uses: EndBug/add-and-commit@v9
        with:
          message: 'RadioTime ${{needs.mpe.outputs.version}} / Release'
          add: '${{ github.workspace }}/setup/RadioTimePlugin.xml'

      - name: Delete XML Artifact
        uses: geekyeggo/delete-artifact@v5
        with:
            name: RadioTimePlugin XML
            failOnError: false

  release:
    name: RadioTime Plugin / Release
    if: "contains(github.event.head_commit.message, '[release]')"
    needs:
      - mpe
      - xml
    permissions:
      contents: write
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: RadioTimePlugin MPE1
          path: release-files

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: RadioTimePlugin Version Description
          path: release-description

      - name: Check Artifacts
        run: |
          ls -l
        working-directory: release-files

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: RadioTime v${{needs.mpe.outputs.version}}
          tag_name: v${{needs.mpe.outputs.version}}
          body_path: release-description/description.txt
          generate_release_notes: true
          files: |
            release-files/*.mpe1

      - name: Delete MPE1 Artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: RadioTimePlugin MPE1
          failOnError: false

      - name: Delete Version Description Artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: RadioTimePlugin Version Description
          failOnError: false

  ci-status:
    name: Build Status
    runs-on: ubuntu-latest
    needs:
      - build
      - mpe
    if: always()
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

  release-status:
    name: Release Status
    if: "contains(github.event.head_commit.message, '[release]')"
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
  
  cache-clear:
    name: Clear cache
    runs-on: ubuntu-latest
    needs:
      - mpe
    if: always()
    steps:
      - name: Clear cache
        uses: easimon/wipe-cache@main
